FROM golang:1.23 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -cover -o /harbor-mcp ./cmd/harbor-mcp/

FROM alpine:3.20
COPY --from=builder /harbor-mcp /harbor-mcp
VOLUME /data
VOLUME /covdata
ENV GOCOVERDIR=/covdata
ENTRYPOINT ["/harbor-mcp"]
CMD ["serve"]
